import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { SidebarNavigation } from "@/components/shared/SidebarNavigation/SidebarNavigation";
import { Flex } from "@chakra-ui/react";
import theme from "@/styles/theme/theme";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TV SHOWS APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: theme.colors.purple[300] }}>
        <Providers> 
          
        <Flex   width="100%"
            textColor="white" backgroundColor="purple.300"
            >
           {children}
          </Flex> 
          </Providers>
      </body>
    </html>
  );
}
